[package]
name = "bdfs-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license-file = "LICENSE"
license = "LGPL-2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.61.0"
